### ISSUE TITLE
install not completing, setupVars.conf missing

### ISSUE THREAD

**Issue by smokes2345** [diginc/docker-pi-hole#278]
This is a... 

- [ ] Request for a new or modified feature
- [ X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Currently using the following command to start the container:
```
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp -p 80:80 \
    -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
    -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
    -e ServerIP="${IP:-$(ip route get 8.8.8.8 | awk '{ print $7; exit }')}" \
    -e ServerIPv6="${IPv6:-$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $11; exit }')}" \
    -e DNS1=192.168.1.1 \
    --restart=always \
    --privileged \
    diginc/pi-hole:latest
```
But /etc/pihole/setupVars.conf does not get created

## Expected Behavior

operational pi-hole container

## Actual Behavior

Container runs, but doesn't answer queries and unable to update lists

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. run docker command above?
2. 
3. 
4. 

## Debug steps I have tried

- [ X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ X] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [X ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X ] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

have tried with volumes and without, do not get a functional container either way

## Your Environment 

* Docker Host Operating System and OS Version: Linux mickey 4.14.42-coreos #1 SMP Thu May 24 21:10:56 UTC 2018 x86_64 AMD G-T56N Processor AuthenticAMD GNU/Linux
* Docker Version: Docker version 18.03.1-ce, build 9ee9f40
* Hardware architecture: x86_64

**Comment by jkrauer** [comment]
This was resolved at #273

**Comment by jpwhite3** [comment]
This is not fixed. I am experiencing a similar on a fresh install:

`Unable to find image 'diginc/pi-hole:latest' locally`
`Trying to pull repository docker.io/diginc/pi-hole ... `
`latest: Pulling from docker.io/diginc/pi-hole`
`55cbf04beb70: Pull complete `
`1a3077ea5303: Pull complete `
`b63c9654aff8: Pull complete `
`e876a61c7750: Pull complete `
`f864def58906: Pull complete `
`73b24cdbc053: Pull complete `
`1899f19508d7: Pull complete `
`Digest: sha256:0f78ea7cdede528ccdc4d5538aff036ae32e4e9da9cf5fabcc7d58b3afddb980`
`Status: Downloaded newer image for docker.io/diginc/pi-hole:latest`
`4e59a4ee91f97d457d04672114a0e47dab9f1f07250c961c583d1b3148ac6c18`
`Your password for https://192.168.1.100/admin/ is [root@localhost pihole]# docker logs `pihole
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.`
`[s6-init] ensuring user provided files have correct perms...exited 0.`
`[fix-attrs.d] applying ownership & permissions fixes...`
`[fix-attrs.d] 01-resolver-resolv: applying... `
`[fix-attrs.d] 01-resolver-resolv: exited 0.`
`[fix-attrs.d] done.`
`[cont-init.d] executing container initialization scripts...`
`[cont-init.d] 20-start.sh: executing... `
` ::: Starting docker specific setup for docker diginc/pi-hole`
`touch: cannot touch '/etc/pihole/setupVars.conf': Permission denied`
`[cont-init.d] 20-start.sh: exited 1.`
`[cont-finish.d] executing container finish scripts...`
`[cont-finish.d] done.`
`[s6-finish] syncing disks.`
`[s6-finish] sending all processes the TERM signal.`
`[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by lachnerd** [comment]
yep  not fixed -  i'm also getting this on a raspberry pi 3 b

**Comment by diginc** [comment]
Can someone with this issue please report back any errors from this most basic run command (with multi-arch image if not x86_x64):

```
docker run -it -e ServerIP='0.0.0.0' -e PH_VERBOSE=1 diginc/pi-hole:latest
```

If that doesn't error out, add your volumes, then show me the output of `ls -lat /path/to/your/volume`

**Comment by lachnerd** [comment]
so i tried:
`docker run -it -d -e ServerIP='0.0.0.0' -e PH_VERBOSE=1 diginc/pi-hole-multiarch:debian_armhf`

Output:
'[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
ARCH=armhf
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=([0]="0")
BASH_SOURCE=([0]="/var/run/s6/etc/cont-init.d/20-start.sh")
BASH_VERSINFO=([0]="4" [1]="4" [2]="12" [3]="1" [4]="release" [5]="arm-unknown-linux-gnueabihf")
BASH_VERSION='4.4.12(1)-release'
CWD=/
DIRSTACK=()
DOCKER_REPO=multiarch/debian-debootstrap
EUID=0
FTL_CMD=no-daemon
GROUPS=()
HOME=/root
HOSTNAME=713b039d2254
HOSTTYPE=arm
IFS=$' \t\n'
IPv6=True
MACHTYPE=arm-unknown-linux-gnueabihf
OPTERR=1
OPTIND=1
OSTYPE=linux-gnueabihf
PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
PHP_ERROR_LOG=/var/log/lighttpd/error.log
PH_VERBOSE=1
PIHOLE_INSTALL=/tmp/ph_install.sh
PPID=210
PS4='+ '
PWD=/
S6OVERLAY_RELEASE=https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-armhf.tar.gz
S6_KEEP_ENV=1
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
ServerIP=0.0.0.0
TAG=debian
TERM=xterm
UBUNTU_SUITE=stretch
UID=0
_=bash
setupVars=/etc/pihole/setupVars.conf
+ bashCmd='bash -e -x'
+ dnsmasq -7 /etc/dnsmasq.d
+ bash -e -x /start.sh
+ export TAG
+ export ServerIP
+ export ServerIPv6
+ export PYTEST
+ export PHP_ENV_CONFIG
+ export PHP_ERROR_LOG
+ export HOSTNAME
+ export WEBLOGDIR
+ export DNS1
+ export DNS2
+ export INTERFACE
+ export IPv6
+ export WEBPASSWORD
+ export WEB_PORT
+ . /bash_functions.sh
++ . /opt/pihole/webpage.sh
+++ setupVars=/etc/pihole/setupVars.conf
+++ dnsmasqconfig=/etc/dnsmasq.d/01-pihole.conf
+++ dhcpconfig=/etc/dnsmasq.d/02-pihole-dhcp.conf
+++ dhcpstaticconfig=/etc/dnsmasq.d/04-pihole-static-dhcp.conf
+++ coltable=/opt/pihole/COL_TABLE
+++ [[ -f /opt/pihole/COL_TABLE ]]
+++ source /opt/pihole/COL_TABLE
++++ [[ -t 1 ]]
+++++ tput colors
++++ [[ 8 -ge 8 ]]
++++ COL_BOLD=''
++++ COL_ULINE=''
++++ COL_NC=''
++++ COL_GRAY=''
++++ COL_RED=''
++++ COL_GREEN=''
++++ COL_YELLOW=''
++++ COL_BLUE=''
++++ COL_PURPLE=''
++++ COL_CYAN=''
++++ COL_WHITE=''
++++ COL_BLACK=''
++++ COL_LIGHT_BLUE=''
++++ COL_LIGHT_GREEN=''
++++ COL_LIGHT_CYAN=''
++++ COL_LIGHT_RED=''
++++ COL_URG_RED=''
++++ COL_LIGHT_PURPLE=''
++++ COL_BROWN=''
++++ COL_LIGHT_GRAY=''
++++ COL_DARK_GRAY=''
++++ TICK='[✓]'
++++ CROSS='[✗]'
++++ INFO='[i]'
++++ QST='[?]'
++++ DONE=' done!'
++++ OVER='\r'
++ setupVars=/etc/pihole/setupVars.conf
++ ServerIP=0.0.0.0
++ ServerIPv6=
++ IPv6=True
+ echo ' ::: Starting docker specific setup for docker diginc/pi-hole'
 ::: Starting docker specific setup for docker diginc/pi-hole
+ validate_env
+ '[' -z 0.0.0.0 ']'
++ nc -4 -w1 -z 0.0.0.0 53
+ [[ '' != '' ]]
+ ip route get 0.0.0.0
+ [[ -n '' ]]
+ prepare_setup_vars
+ touch /etc/pihole/setupVars.conf
+ change_setting IPV4_ADDRESS 0.0.0.0
+ delete_setting IPV4_ADDRESS
+ sed -i /IPV4_ADDRESS/d /etc/pihole/setupVars.conf
+ add_setting IPV4_ADDRESS 0.0.0.0
+ echo IPV4_ADDRESS=0.0.0.0
+ change_setting IPV6_ADDRESS ''
+ delete_setting IPV6_ADDRESS
+ sed -i /IPV6_ADDRESS/d /etc/pihole/setupVars.conf
+ add_setting IPV6_ADDRESS ''
+ echo IPV6_ADDRESS=
+ setup_web_port ''
+ local 'warning=WARNING: Custom WEB_PORT not used'
+ [[ -z '' ]]
+ return
+ setup_web_password ''
+ '[' -z '' ']'
++ tr -dc _A-Z-a-z-0-9
++ head -c 8
+ WEBPASSWORD=0Omau8XA
+ echo 'Assigning random password: 0Omau8XA'
Assigning random password: 0Omau8XA
+ set -x
+ [[ 0Omau8XA == '' ]]
+ pihole -a -p 0Omau8XA 0Omau8XA
  [✓] New password set
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
                        "ServerIP" => "0.0.0.0",
                        "VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Testing DNSmasq config: dnsmasq: syntax check OK.
::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
+ gravity.sh
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 155097
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 131875
  [i] Nothing to whitelist!
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
pihole-FTL: no process found
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
++ pgrep dnsmasq
+ kill -9 216
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dnsmasq
Starting pihole-FTL (no-daemon)
Starting crond
Starting lighttpd
[services.d] done.
dnsmasq: started, version 2.76 cachesize 10000
dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: read /etc/hosts - 7 addresses
dnsmasq: read /etc/pihole/local.list - 2 addresses
dnsmasq: failed to load names from /etc/pihole/black.list: No such file or directory
dnsmasq: read /etc/pihole/gravity.list - 131875 addresses
dnsmasq: 1 127.0.0.1/45908 query[A] pi.hole from 127.0.0.1
dnsmasq: 1 127.0.0.1/45908 /etc/pihole/local.list pi.hole is 0.0.0.0
'

**Comment by jpwhite3** [comment]
For reference, I'm running on CentOS 7.5 with Docker version 1.13.1 (build dded712/1.13.1)

**Ran the following with no errors. Out same essentially same as @lachnerd:**
`docker run -it -e ServerIP='0.0.0.0' -e PH_VERBOSE=1 diginc/pi-hole:latest`

**I then added the volumes:**
`docker run -d -v /tmp/docker/pihole/:/etc/pihole/ -v /tmp/docker/dnsmasq.d/:/etc/dnsmasq.d/ -e ServerIP=0.0.0.0 -e PH_VERBOSE=1 diginc/pi-hole:latest`

**The above dies with the following error:**
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.`
`[s6-init] ensuring user provided files have correct perms...exited 0.`
`[fix-attrs.d] applying ownership & permissions fixes...`
`[fix-attrs.d] 01-resolver-resolv: applying... `
`[fix-attrs.d] 01-resolver-resolv: exited 0.`
`[fix-attrs.d] done.`
`[cont-init.d] executing container initialization scripts...`
`[cont-init.d] 20-start.sh: executing... `
`+ bashCmd='bash -e -x'`
`+ dnsmasq -7 /etc/dnsmasq.d`
`dnsmasq: cannot access directory /etc/dnsmasq.d: Permission denied`
`[cont-init.d] 20-start.sh: exited 3.`
`[cont-finish.d] executing container finish scripts...`
`[cont-finish.d] done.`
`[s6-finish] syncing disks.`
`[s6-finish] sending all processes the TERM signal.`
`[s6-finish] sending all processes the KILL signal and exiting.`

**I then took a look at the filesystem and found no files had been created, only directories:**
`[root@localhost docker]# ls -lat /tmp/docker/`
`total 16`
`drwxrwxrwt. 17 root root 4096 Jul 26 20:11 ..`
`drwxrwxrwx.  4 root root 4096 Jul 26 20:05 .`
`drwxr-xr-x.  2 root root 4096 Jul 26 20:05 dnsmasq.d`
`drwxr-xr-x.  2 root root 4096 Jul 26 20:05 pihole`

`[root@localhost docker]# ls -lat /tmp/docker/pihole/`
`total 8`
`drwxr-xr-x. 2 root root 4096 Jul 26 20:05 .`
`drwxrwxrwx. 4 root root 4096 Jul 26 20:05 ..`

`[root@localhost docker]# ls -lat /tmp/docker/dnsmasq.d/`
`total 8`
`drwxr-xr-x. 2 root root 4096 Jul 26 20:05 .`
`drwxrwxrwx. 4 root root 4096 Jul 26 20:05 ..`

**Comment by diginc** [comment]
Thanks, next I'm curious about the output of `docker info`?  

I'm starting to wonder if this isn't caused by a difference in [storage driver types](https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-ce)

Other debug steps you could try are:  I confirmed all of these worked on ubuntu 14, aufs storage driver, docker-ce 18.06.

```
# Enter docker container without running startup scripts, just bash for debug
docker run -it --rm -v /tmp/docker/pihole/:/etc/pihole/ -v /tmp/docker/dnsmasq.d/:/etc/dnsmasq.d/ -e ServerIP=0.0.0.0 --entrypoint=bash diginc/pi-hole:latest

# Volume permission view from inside container (root owned volume directories and any files inside)
ls -lat {/etc/dnsmasq.d,/etc/pihole}

# Test creating file as root docker user
touch {/etc/dnsmasq.d,/etc/pihole}/newfile

# Review results of touch again if they didn't error you'll see the 'newfile' in the dirs
ls -lat {/etc/dnsmasq.d,/etc/pihole}

# Run the permission denied error we've previously seen in the foreground, but without any start up scripts
dnsmasq -7 /etc/dnsmasq.d/ --no-daemon
#  ctrl+c to quit dnsmasq

# Run dnsmasq with a non volume instead to compare also, should work no problem.
dnsmasq -7 "$(mktemp -d)" --no-daemon
# ctrl+c to quit dnsmasq, `exit` to leave the docker.
```

Related to the storage driver, you could also run 'mount' inside the container which should show the volume mounts and what options they're mounted with.

```
root@e504642db1e1:/# mount
none on / type aufs (rw,relatime,si=e9261efd14629d79,dio,dirperm1)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (ro,nosuid,nodev,noexec,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
systemd on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,name=systemd)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
/dev/dm-1 on /etc/pihole type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/dm-1 on /etc/dnsmasq.d type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/dm-1 on /etc/resolv.conf type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/dm-1 on /etc/hostname type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/dm-1 on /etc/hosts type ext4 (rw,relatime,errors=remount-ro,data=ordered)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
proc on /proc/asound type proc (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_stats type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime)
tmpfs on /sys/firmware type tmpfs (ro,relatime)
```

**Comment by diginc** [comment]
Also we've seen some weirdness on older versions of docker @jpwhite3 in another issue which was resolved by upgrading.

I'd encourage upgrading beyond `Docker version 1.13.1` to docker-ce if possible.

**Comment by diginc** [comment]
@smokes2345 did you still have this problem?
